// Package Manager Roles.
//? 1. Installation of the packages.
//? 2. Version management.
//? 3. Manging dependencies.
//? 4. Publishing packages


// Package-lock.json Roles.
//? 1. Auto generated by npm.
//? 2. Helps with consistency of versions on different machine
//? 3. Prenents unwanted updates.

// Understading the versions of the packages.
 
//?       Sr           Version                                          Details
//        1.         Major 1.0.0                    Incompatible changes, might not function as before
//        2.         Minor 1.1.0                    New features with backward-compatibility
//        3.         Patch 1.1.1                    Bug fixes, no significant changes made


//        4.         Tilde (~)                      npm can install latest //! patch releases.
//        5.         Caret(^)                       npm can install latest //! minor releases.
//        6.         No Symbol                      npm will install exact version.